# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7531d9860e10cbaffda1e6f28dbb4ca7b43308c9318761487c6bf595b9256e2445a89853317e6754628af980dadeea936efd5612e0a0d5a43c4a7b186e9123c8

test:
  secret_key_base: 048ab4d2b3e57fcb4f31a6113809a6120f0f64b675571eaa7447c4ed30cc74f70b34aab54016dcd0b0e80f753e7688378ad522a83cc5a587133f6d67c2b62f6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
